Import Debian changes 5.2.6-5
celery (5.2.6-5) unstable; urgency=medium
.
  * Team upload.
.
  [ Bas Couwenberg ]
  * Add upstream patch to fix FTBFS with python3.11.
    (closes: #1028148)
.
  [ Paul Wise ]
  * debian/copyright: replace Unicode linebreaks with regular linebreaks.
  * Declare compliance with Debian Policy 4.6.2, no changes needed.
  * Drop python3-nose from build-deps, already switched to pytest
    (Closes: #1018326)
  * Correct package names listed in celery wrapper script.
  * Update broken link to daemonization docs
  * Add more upstream metadata
  * Update the homepage
.
celery (5.2.6-4) unstable; urgency=medium
.
  * Actually bump billiard dependencies to 4.0.2
.
celery (5.2.6-3) unstable; urgency=medium
.
  * Team upload.
  * Backport upstream patch to fix compatibility with billiard 4.0.2 (Closes: #1020137)
.
celery (5.2.6-2) unstable; urgency=medium
.
  * Add upstream patch to fix compatibility with billiard 4 (Closes:
    #1015028).
  * Bump Standards-Version to 4.6.1.0.

diff --git a/debian/wrappers/celery b/debian/wrappers/celery
--- a/debian/wrappers/celery
+++ b/debian/wrappers/celery
@@ -11,7 +11,7 @@ elif command -v python2.6 > /dev/null && test -e /usr/lib/python2.6/dist-package
 then
     exec python2.6 "$0" "$@"
 else
-    echo "Cannot find installed version of python-django or python3-django." >&2
+    echo "Cannot find installed version of python-celery or python3-celery." >&2
     exit 1
 fi
 
